### PR TITLE
fix bug where empty tabs are opened when opening file from within pinned tab

### LINKED ISSUE #430: Empty tab(s) open when opening a note while on a pinned tab
**Describe the bug**
While on a pinned tab, if I open a note (either through the files explorer or by opening a note in Graph View), along with a new tab containing the note, another unwanted tab is created containing nothing except for the "No file is open" screen.

**To Reproduce**
1. Pin a tab and then switch to it.
2. Using either the file explorer or graph view (if the graph view is in the pinned tab), open another note while still on the pinned tab.

**Expected behavior**
When opening a note while on a pinned tab, only one new tab containing the note should appear.

**Screenshots**
image
image

**Additional context**
I am running Obsidian on Linux, with NixOS as my distro. Screenshots are from a vault I created to test this bug, and there are no other plugins other than the default Core plugins.

### PR DESCRIPTION
**Pull request by jaycenhorton**
Fixes #430 wherein opening a file when you are currently viewing a pinned tab causes empty tabs to open in addition to the file selected.

### CODE REVIEW

File: src/emoji.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import twemoji from 'twemoji';
 import { EmojiStyle } from './settings/data';
 
 const regex =
-  /(\p{Emoji}|\p{Emoji_Presentation}|\p{Emoji_Modifier}|\p{Emoji_Modifier_Base}|\p{Emoji_Component}|\p{Extended_Pictographic})/gu;
+  /(?!#)(\p{Emoji}|\p{Emoji_Presentation}|\p{Emoji_Modifier}|\p{Emoji_Modifier_Base}|\p{Emoji_Component}|\p{Extended_Pictographic})/gu;
```
Comment (jaycenhorton) [inline src/emoji.ts:5]: refined matcher to explicitly exclude the hash ("#") symbol

this was necessary because the "#" character is recognized as a base for key-cap emoji sequences, like #️⃣, and was causing inadvertent matching of markdown headers. The negative look-ahead (?!#) at the beginning of the pattern ensures that the regex skips over instances of the "#" character, while still matching other emoji-related Unicode properties

**Comment by FlorianWoelki** [comment]
thank you for your contribution!

**Review by FlorianWoelki — APPROVED** [review]
